[package]
name = "v-m-io-back"
authors.workspace = true
version.workspace = true
edition.workspace = true
description = "v-m.io types"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/v-m-io-types"
repository = "https://github.com/voidmerge/v-m.io"
keywords = [ "p2p", "verify", "verifiable" ]
categories = [ "database", "database-implementations", "network-programming", "web-programming" ]

[dependencies]
tokio = { workspace = true, features = ["full"] }
hyper = { workspace = true, features = ["server"] }
hyper-util = { workspace = true, features = ["server", "server-auto", "tokio"] }
http-body-util = { workspace = true }
lru = { workspace = true }
mlua = { workspace = true, features = ["luajit"] }
