[package]
name = "v-m-io-db"
authors.workspace = true
version.workspace = true
edition.workspace = true
description = "v-m.io db"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/v-m-io-db"
repository = "https://github.com/voidmerge/v-m.io"
keywords = [ "p2p", "verify", "verifiable" ]
categories = [ "database", "database-implementations", "network-programming", "web-programming" ]

[dependencies]
aegis = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
rand = { workspace = true }
rusqlite = { workspace = true, features = ["modern_sqlite", "bundled-sqlcipher-vendored-openssl"] }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
zeroize = { workspace = true }

[dev-dependencies]
tempfile = "3"
